Add portuguese translation 💪🇦🇴🇧🇷🇨🇻🇹🇱🇬🇶🇬🇼🇲🇴🇲🇿🇵🇹🇸🇹💪
amugofjava/anytime_podcast_player pull request #58
Opened 2021-09-22 10:19 UTC by ademar111190

Hi, I just add this Portuguese translation on Breez fork so I'm sharing it here now.

About the translation, Brazilian Portuguese is my mother language, there are important differences in Brazilian Portuguese and other variants, especially on the conjugation of the second person (singular and plural), gerund x periphrastic, vocabulary, etc… So to have a _wide_ Portuguese support it is necessary at least the European and African variations, nevertheless, it is still the same language so all Portuguese speakers can understand it perfectly.

<img src="https://user-images.githubusercontent.com/1225438/131668016-9a6cf505-5a26-455a-bfd3-7d83eef2bbfb.png" width="50%"/>

2021-09-24 06:53 UTC, amugofjava commented
Thank you @ademar111190 that's fantastic.

2021-10-13 05:54 UTC, amugofjava commented
Hi @ademar111190,

No, I'm not waiting for anything from you - just not had chance yet to merge this PR.

Thanks.

2022-02-19 22:06 UTC, bitcoinuser commented on lib/l10n/intl_pt.arb
> +  "unsubscribe_button_label": "NÃO SEGUIR",
```suggestion
  "unsubscribe_button_label": "DEIXAR DE SEGUIR",
```

2022-02-19 22:06 UTC, bitcoinuser commented on lib/l10n/intl_pt.arb
> +  "unsubscribe_label": "Não Seguir",
```suggestion
  "unsubscribe_label": "Deixar de seguir",
```

2022-02-19 22:07 UTC, bitcoinuser requested changes
Minor changes

2022-03-20 14:27 UTC, amugofjava commented
Thank you both @ademar111190 & @bitcoinuser for your contributions. I have not merged these yet as I am currently working on new features and will have new text strings. Would you be happy to translate these new strings when they become available?

2023-10-06 13:39 UTC, closed without merging